#!/usr/bin/env bash
# 4 bad luck, 8 good luck

i=1

while [ "$i" -lt 11 ]; do

  # if 4 it prints "bad luck" elif 8 prints "good luck"
  if [ "$i" -eq 4 ]; then
    echo "bad luck"
  elif [ "$i" -eq 8 ]; then
    echo "good luck"
  else
    echo "Best School"
  fi

  ((i++))
done
