#!/usr/bin/env bash
# Makes the server to be run by nginx user
chmod 644 /etc/nginx/nginx.conf
sed -Ei 's/(listen (\[::\]:)?80) /\180 /' /etc/nginx/sites-enabled/default
sed -Ei 's/\s*#?\s*user .*/user nginx;/' /etc/nginx/nginx.conf
su nginx -s /bin/bash -c 'service nginx restart'
